version: '3.8'
services:

  mongo:
      image: mongo
      container_name: project-office-db
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: kyrian
      volumes:
        - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        - ./mongo-volume:/data/db
      ports:
        - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: adminweb
      ME_CONFIG_BASICAUTH_PASSWORD: kyrian
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: kyrian
      ME_CONFIG_MONGODB_SERVER: mongo
    restart: unless-stopped
    links:
      - mongo
